# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14
# используем режим обычного пользователя для сборки проекта..
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Здесь Вставляем свой токен для интеграции codecov
env:
    global:
      - CODECOV_TOKEN="cec8c962-9a91-4dac-ac24-9049b8ac5838"

# Отправлять уведомление на почту xyligan2222@yandex.ru если сборка упала

notifications:
  email:
    recipients:
      -xyligan2222@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always